### ISSUE TITLE
Expression could return `Value` directly and don't need to set the eval result to the private data member `result_`(

### ISSUE THREAD

**Issue by jievince** [vesoft-inc/nebula-common#594]
Currently, `eval()` of expression returns a `const value&`. And most expressions store the result that `eval`ed to a `result_` and then return it to the caller. The caller most often picks it up with a copy of the value.
```
virtual const Value& eval(ExpressionContext& ctx) = 0;
```
```
 Value val = col->expr()->eval(ctx(iter.get()));
```
So this caused two copy overhead.
The reason why most of the callers use copy of value to pick the `eval`ed result is some of the expressions don't store the `eval`ed result to `result_`:
```
const Value& InputPropertyExpression::eval(ExpressionContext& ctx) {
    return ctx.getInputProp(prop_); // The value returned comes from the valueMap of ExecutionContext, so it shouldn't be moved by the caller
}
```

Moreover, it is a bit strange to store the `eval`ed result that is only valid for the current row to the expression class.

We could let `eval()` return  a `Value` and don't need to store the `eval`ed result to `result_`.
Meanwhile, `AggregateExpression` is special. It's not stateless, so it should store the `eval`ed result to `result_`.

**Comment by CPWstatic** [comment]
We had a benchmark for these two situation.
